### ISSUE TITLE
Consider changing the link for 'origin'

### ISSUE THREAD

**Issue by jwatt** [w3c/webappsec-secure-contexts#1]
The link for 'origin' is currently https://tools.ietf.org/html/rfc6454#section-3.2 but should perhaps be https://html.spec.whatwg.org/multipage/browsers.html#origin

**Comment by annevk** [comment]
Yeah, the Origin RFC is more or less obsolete, we shouldn't use it.

**Comment by jwatt** [comment]
Or maybe http://www.w3.org/TR/html5/browsers.html#origin I guess, since the spec sometimes seems to link to the W3C version of HTML5.

**Comment by mikewest** [comment]
Oh, right. One of my favourite topics. I'll update this to drop the RFC reference.

**Comment by jwatt** [comment]
This was fixed in 502a9ae15038f4dd1db540aea1137ca10ce01a51.
