### ISSUE TITLE
Clarification of changes to WebIDL

### ISSUE THREAD

**Issue by deian** [w3c/webappsec-secure-contexts#16]
It wasn't clear from reading the [WebIDL section](
https://w3c.github.io/webappsec-secure-contexts/#monkey-patching-idl) if `[SecureContext]` can be used to control whether interfaces or just interface members are restricted. From looking at your WebIDL PR, I gathered that we can indeed use it for interfaces (yay!). I'm guessing you didn't get a chance to write the text for that section. I can work on a PR to update some of it if it would be useful.

**Comment by annevk** [comment]
You should probably ping @mikewest directly. I'm sure he'd appreciate the help.

**Comment by mikewest** [comment]
1. PRs happily accepted.

2. I haven't put much work into this section while the WebIDL patch is still in flux. I'll have an updated version of that patch today or Monday based on bz's feedback, so I'm hopeful that we can agree on behavior in the relatively near future. *shrug*

**Comment by jwatt** [comment]
I think all the normative text will be in the WebIDL 2 spec, added by heycam now that he's picked up mike's PR.

**Comment by mikewest** [comment]
@heycam took care of it, because he is nice.
