### ISSUE TITLE
Example describing window.opener is garbled.

### ISSUE THREAD

**Issue by jyasskin** [w3c/webappsec-secure-contexts#17]
[Example 5](https://w3c.github.io/webappsec-secure-contexts/#example-e024fc75) says:

> That is, if the new window can access the non-secure context via window.opener, and the non-secure context can access the secure context by grabbing a reference to the window, **then it , because** it is a new top-level browsing context delivered over an authenticated and encrypted channel.

The bold part is garbled.

**Comment by mikewest** [comment]
Yup. I think I meant to remove that example entirely as it's redundant with the test in example 4. Thanks for the heads up!
