### ISSUE TITLE
Request to participate

### ISSUE THREAD

**Issue by rapcatcher801** [w3c/webappsec-secure-contexts#29]
[https://docs.google.com/spreadsheets/d/1hnCoaJTXkfSSHD5spISJ76nqbDcOVNMamgByiz3QWLA/edit?pli=1#gid=0]

**Comment by mikewest** [comment]
I don't understand what you're asking for. Could you clarify? :)

**Comment by mikewest** [comment]
Closing this out. Please feel free to reopen if I've misunderstood something.
