### ISSUE TITLE
Consider linking to just the WHATWG version of HTML5 or just the W3C version

### ISSUE THREAD

**Issue by jwatt** [w3c/webappsec-secure-contexts#3]
Right now the text sometimes links to the WHATWG version of HTML5 and at other times to the W3C version. Maybe there's a reason for this, but it seems inconsistent.

**Comment by mikewest** [comment]
I'm linking to W3C when the definitions match up well enough, and WHATWG when they don't.
I'll argue with folks about it a bit when we try to transition the document to "candidate recommendation", and they'll make me link to W3C all the time even if it doesn't make sense, and I'll be sad. *shrug*
