### ISSUE TITLE
Missing ""s when referring to results of "Is origin potentially trustworthy?

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec-secure-contexts#35]
Step 6 of "Is settings object a secure context?" says

> If the result of executing the §3.2 Is origin potentially trustworthy? algorithm on origin is not Potentially Trustworthy, then return "Not Secure".

but the return value of 3.2 is a string, so this should be

> If the result of executing the §3.2 Is origin potentially trustworthy? algorithm on origin is not "Potentially Trustworthy", then return "Not Secure".

Similarly 7.2 says

> even though §3.2 Is origin potentially trustworthy? would normally return Not Trusted.

but should say

> even though §3.2 Is origin potentially trustworthy? would normally return "Not Trusted".

**Comment by mikewest** [comment]
Thanks!
