### ISSUE TITLE
Transition to CR.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec-secure-contexts#39]
I think we're ready to transition to CR. Perhaps you share that belief?

https://w3c.github.io/webappsec-secure-contexts/CR.html is up for your review.

+1s and emojified responses welcome here. Alternatively, if you think something's not ready yet, file an issue and I'll link it up here.

CfC posted to the list at https://lists.w3.org/Archives/Public/public-webappsec/2016Jul/0032.html.

Discussion of references to WHATWG docs at https://github.com/w3c/webappsec-secure-contexts/issues/9.

**Comment by mikewest** [comment]
@titanous noted https://github.com/w3c/webappsec-secure-contexts/issues/40, which won't have any normative effect, but is an important editorial change to make before CR.

**Comment by mikewest** [comment]
@jakearchibald filed https://github.com/w3c/webappsec-secure-contexts/issues/42, which requests normative change to the `noopener` bits of the spec.

**Comment by mikewest** [comment]
@w3ctag suggests linking to their "Securing the Web" finding: https://www.w3.org/2001/tag/doc/web-https

**Comment by annevk** [comment]
This either has follow-ups or is done.
