### ISSUE TITLE
Section "Is origin potentially trustworthy?", second paragraph, second sentence does not read well

### ISSUE THREAD

**Issue by dbates-wk** [w3c/webappsec-secure-contexts#44]
Section Is origin potentially trustworthy?, second paragraph, second sentence, reads:

>  In particular, the user agent SHOULD treat file URLs and as potentially trustworthy.

This sentence does not read well because of the presence of the word "and". It should read:

In particular, the user agent SHOULD treat file URLs as potentially trustworthy.

**Comment by mikewest** [comment]
Thanks!
