### ISSUE TITLE
Section "Is origin potentially trustworthy?", step 8 of algorithm returns "Not Trusted" 

### ISSUE THREAD

**Issue by dbates-wk** [w3c/webappsec-secure-contexts#45]
Step 8 of the algorithm in section "Is origin potentially trustworthy?" returns "Not Trusted". This disagrees with the possible return values stated in the paragraph above the algorithm:
> Given an origin (origin), the following algorithm returns "Potentially Trustworthy" or "Not Trustworthy" as appropriate.

**Comment by mikewest** [comment]
Thanks!
