### ISSUE TITLE
Creator context security used incorrectly

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-secure-contexts#48]
The document obtains it from a document, but HTML defines it only existing on a browsing context. Also, I think we should probably redesign how this works, per https://github.com/whatwg/html/issues/2645. Thoughts appreciated.

**Comment by mikewest** [comment]
Dropped its usage from the spec. I suspect we can safely remove it from HTML as well (do you know of any other inclusions?)

**Comment by annevk** [comment]
Pretty sure it's just Secure Contexts. Filed a PR to remove it.
