### ISSUE TITLE
Error msg (https://goo.gl/Y0ZkNV)  instead of giving the latitude and longitude

### ISSUE THREAD

**Issue by JTurcott** [w3c/webappsec-secure-contexts#53]
Why is Chrome's browser reporting and obscure error message instead of giving the correct latitude and longitude when using the free geolocation and geolocation html5?  These 2 web sites (ClickMeInfo.com and Mallocity.com) using the exact same software code had been working perfectly for over 2 years, but earlier this year (2017), instead of reporting the client's latitude and longitude, this Chrome error link is giving without any explanation as to how to resolve this issue.

**Comment by annevk** [comment]
You need to move your websites to HTTPS.
