### ISSUE TITLE
Consider "potentially trustworthy" for responses

### ISSUE THREAD

**Issue by jyasskin** [w3c/webappsec-secure-contexts#63]
https://github.com/WICG/webpackage/pull/352 would like to figure out if a [response](https://fetch.spec.whatwg.org/#responses) is potentially trustworthy. It's straightforward to check if the response's URL or origin is potentially trustworthy, but this differs from the calculation for [environment settings objects](https://w3c.github.io/webappsec-secure-contexts/#is-settings-object-contextually-secure) in that it allows responses with an HTTPS state of "deprecated" and doesn't pay any attention to the [sandbox CSP directive](https://w3c.github.io/webappsec-csp/#directive-sandbox).

This spec is a more reliable place to define this than the web packaging spec, since security folks won't think to update that if new information gets added to responses.

**Comment by annevk** [comment]
https://github.com/whatwg/html/issues/4930 needs something similar I think. In particular determining the secure context state of a response that is being navigated to combined with its future parent document (or null) or some such.

**Comment by annevk** [comment]
Now that HTTPS state is gone I don't think this is a problem anymore. Let me know if I missed anything.
