### ISSUE TITLE
secure contexts and Workers created from data URLs

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webappsec-secure-contexts#74]
https://w3c.github.io/webappsec-secure-contexts/#is-settings-object-contextually-secure
states:

 - If _global_ is a WorkerGlobalScope, then:
   - For each Document (_document_) in _global_’s owner set:
     - Assert: Workers must be same-origin with the context that created them, so document’s relevant settings object's origin and HTTPS state is the same as global’s relevant settings object's origin and HTTPS state.
     - If _document_’s relevant settings object is not contextually secure, return "Not Secure".
   - Return "Secure".
 - ...

The assertion is confusing or wrong, because a worker can be created from a data URL, and in that case the worker is __not__ same origin with its parent context.

**Comment by yutakahirano** [comment]
cc: @annevk @nhiroki

My understanding is that a worker should inherit its owner set documents' HTTPS state, and the assertion should be fixed accordingly. Please let me know if you think otherwise.

Related to https://github.com/web-platform-tests/wpt/pull/22929.

**Comment by annevk** [comment]
Thanks for spotting that, agreed! See also https://github.com/whatwg/html/issues/5254 for some additional complexity due to data URL workers.

**Comment by nhiroki** [comment]
+1.

For reference, the [HTML spec](https://html.spec.whatwg.org/multipage/workers.html#script-settings-for-workers) defines that a data URL worker has an opaque origin:

> The origin:
> Return a unique opaque origin if worker global scope's url's scheme is "data", and inherited origin otherwise.

And, the [Fetch spec](https://fetch.spec.whatwg.org/#scheme-fetch) defines a response for a data URL has fetch client's HTTPS state, that is, the document's HTTPS state:

> "data":
> 3. Return a response whose status message is `OK`, header list consist of a single header whose name is `Content-Type` and value is dataURLStruct’s MIME type, serialized, body is dataURLStruct’s body, and HTTPS state is request’s client’s HTTPS state if request’s client is non-null.

**Comment by annevk** [comment]
https://github.com/whatwg/html/pull/5659 resolves this, but since this specification doesn't appear to be maintained, leaving this open for now for visibility.

**Comment by annevk** [comment]
Solved by #84.
