### ISSUE TITLE
Behavior of accessing properties in non-secure contexts

### ISSUE THREAD

**Issue by jungkees** [w3c/webappsec-secure-contexts#8]
What would be the desired behavior of accessing attributes/methods in non-secure context? Shouldn't the context object itself be exposed (which the attributes/methods belong to)? Or Should it be exposed and the actual access/invocation to them throw?

Currently service worker spec expose the object and throw when the attributes/methods are accessed.

Related issue in IDL: https://github.com/heycam/webidl/pull/65
Background: 
 - https://github.com/slightlyoff/ServiceWorker/issues/687
 - https://github.com/slightlyoff/ServiceWorker/issues/754

**Comment by mikewest** [comment]
This is being hammered out in the `[SecureContext]` IDL attribute. It won't be defined in this document except by reference: https://github.com/heycam/webidl/pull/65
